
{/* Productos Pizzas 2X1 */}
export const pizzas2x1 = [
  {
    id: "al-pastor",
    name: "Al Pastor",
    description: "Carne al Pastor, Piña y Cebolla",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "hawaiana",
    name: "Hawaiana",
    description: "Piña, Jamón y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "hawaiana-campestre",
    name: "Hawaiana Campestre",
    description: "Pollo, Elote, Piña y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "hawaiana-napoli",
    name: "Hawaiana Napoli",
    description: "Pierna, Tocino, Piña y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "hawaiana-especial",
    name: "Hawaiana Especial",
    description: "Pepperoni, Carne Molida, Champiñones, Aceitunas, Elote, Piña y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "carnes-frias",
    name: "Carnes Frías",
    description: "Pierna, Salchicha, Jamón, Lomo y Pepperoni",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "4-stagioni",
    name: "4 Stagioni",
    description: "Jamón, Champiñones, Aceitunas y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "ortolana",
    name: "Ortolana",
    description: "Champiñones, Pimiento Verde, Cebolla, Jalapeños y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "vegetariana-queen",
    name: "Vegetariana Queen",
    description: "Champiñones, Pimiento Verde, Cebolla, Aguacate, Aceitunas y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "mozzarella-napoli",
    name: "Mozzarella Napoli",
    description: "Jamón, Salami, Chorizo, Pimiento Verde, Champiñones, Cebolla y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "mexicanisima",
    name: "Mexicanísima",
    description: "Pierna, Pollos, Jalapeños, Aguacate y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "peperomania",
    name: "Peperomania",
    description: "Pepperoni, Chorizo, Cebolla, Pimiento Verde y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "ranchera",
    name: "Ranchera",
    description: "Chorizo, Jalapeños, Cebolla, Frijoles y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "azteca",
    name: "Azteca",
    description: "Tocino, Frijoles, Jalapeños, Cebolla, Champiñones y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "capri",
    name: "Capri",
    description: "Carne Molida, Frijoles, Jalapeños, Cebolla y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "alemana",
    name: "Alemana",
    description: "Lomo, Salchicha, Jamón, Jalapeños, Cebolla y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "suprema",
    name: "Suprema",
    description: "Carne Molida, Salchicha, Champiñones, Chorizo, Cebolla y Tocino y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "guanajuato",
    name: "Guanajuato",
    description: "Frijoles, Cebolla, Tocino, Jamón, Champiñones, Pimiento Verde, Mayonesa, Aguacate y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "pepperoni-especial",
    name: "Pepperoni Especial",
    description: "Pepperoni, Champiñones, Carne Molida y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "siciliana",
    name: "Siciliana",
    description: "Camarón, Atún, Aceitunas y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "cubana",
    name: "Cubana",
    description: "Atún, Jalapeños, Jitomate y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "napoli-especial",
    name: "Napoli Especial",
    description: "Camarones, Ostión Ahumado, Jalapeños, Cebolla, Aguacate y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
  {
    id: "supernapoli",
    name: "Supernapoli",
    description: "Atún, Mejillones, Ostión Ahumado, Aceitunas, Cebolla y Queso",
    sizes: { CH: 199, MED: 279, GDE: 309, FAM: 349 },
    category: "2x1",
  },
]

  {/* Productos Paquetes */}
export const complementos = [
  {
    id: "paquete-alla-bolognese",
    name: "Paquete Spaguetti Alla Bolognese",
    description: "Salsa, Carne Molida y Queso",
    price: 109,
    image: "/spaguetti-bolognese.jpg",
    category: "Spaguetti",
  },
  {
    id: "paquete-della-casa",
    name: "Paquete Spaguetti Della Casa",
    description: "Jamón, Champiñones y Queso",
    price: 109,
    image: "/spaguetti-with-ham.jpg",
    category: "Spaguetti",
  },
  {
    id: "paquete-napoli",
    name: "Paquete Spaguetti Napoli",
    description: "Salsa Napoli y Queso",
    price: 109,
    image: "/spaguetti-napoli.jpg",
    category: "Spaguetti",
  },
  {
    id: "paquete-carbonarina",
    name: "Paquete Spaguetti Alla Carbonarina",
    description: "Tocino, Champiñones, Cebolla y Queso",
    price: 109,
    image: "/spaguetti-carbonara.jpg",
    category: "Spaguetti",
  },
]

